import type Database from 'better-sqlite3';

/** Max rows per multi-row INSERT statement. */
const BATCH_ROWS = 100;

/**
 * Max UTF-8 byte length of a single INSERT statement. D1 / wrangler enforce a
 * per-statement length limit (SQLITE_TOOBIG on `--local`), so a batch is
 * flushed early when the next row would push the statement past this budget.
 * A single row larger than the budget is still emitted as its own single-row
 * INSERT (counted in `DumpResult.oversizedStatements`).
 */
export const STATEMENT_BYTE_BUDGET = 90_000;

/** Insert order respects foreign-key dependencies. */
const TABLES: { name: string; columns: string[]; orderBy: string }[] = [
  { name: 'projects', columns: ['id', 'slug', 'name'], orderBy: 'id' },
  { name: 'users', columns: ['id', 'name'], orderBy: 'id' },
  {
    name: 'stories',
    columns: [
      'id',
      'project_id',
      'title',
      'story_type',
      'current_state',
      'priority',
      'estimate',
      'requested_by_id',
      'created_at',
      'accepted_at',
      'deadline',
      'description',
      'url',
      'extra',
    ],
    orderBy: 'id',
  },
  {
    name: 'story_owners',
    columns: ['story_id', 'user_id', 'position'],
    orderBy: 'story_id, position',
  },
  {
    name: 'story_labels',
    columns: ['story_id', 'label'],
    orderBy: 'story_id, label',
  },
  {
    name: 'comments',
    columns: ['story_id', 'seq', 'author_id', 'commented_on', 'body'],
    orderBy: 'story_id, seq',
  },
  {
    name: 'tasks',
    columns: ['story_id', 'seq', 'description', 'status'],
    orderBy: 'story_id, seq',
  },
  {
    name: 'attachments',
    columns: ['story_id', 'filename', 'size', 'rel_path'],
    orderBy: 'story_id, filename',
  },
];

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'bigint') return value.toString();
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * Batch rows into multi-row INSERT statements. A batch is flushed when it
 * reaches {@link BATCH_ROWS} rows or when adding the next row would push the
 * statement's UTF-8 byte length past `budget`. A single row whose statement
 * alone exceeds the budget is still emitted, as its own single-row INSERT.
 */
export function buildInsertStatements(
  tableName: string,
  columns: string[],
  rows: unknown[][],
  budget: number = STATEMENT_BYTE_BUDGET,
): string[] {
  const statements: string[] = [];
  const prefix = `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES\n`;
  const baseBytes = Buffer.byteLength(prefix, 'utf8') + 1; // + trailing ';'

  let tuples: string[] = [];
  let bytes = baseBytes;
  const flush = (): void => {
    if (tuples.length === 0) return;
    statements.push(`${prefix}${tuples.join(',\n')};`);
    tuples = [];
    bytes = baseBytes;
  };

  for (const row of rows) {
    const tuple = `(${row.map(sqlLiteral).join(',')})`;
    const tupleBytes = Buffer.byteLength(tuple, 'utf8') + 2; // + ',\n' separator
    if (
      tuples.length > 0 &&
      (tuples.length >= BATCH_ROWS || bytes + tupleBytes > budget)
    ) {
      flush();
    }
    tuples.push(tuple);
    bytes += tupleBytes;
  }
  flush();
  return statements;
}

export interface DumpResult {
  sql: string;
  /**
   * Number of emitted statements whose UTF-8 byte length still exceeds the
   * budget — necessarily single-row INSERTs of oversized rows.
   */
  oversizedStatements: number;
}

/**
 * Generate a single Cloudflare-D1-compatible SQL script that recreates the
 * whole dataset: schema DDL, batched multi-row INSERTs (bounded by both row
 * count and {@link STATEMENT_BYTE_BUDGET}), then the two FTS rebuild
 * statements. No PRAGMA / BEGIN / COMMIT (wrangler handles batching).
 */
export function generateDump(
  db: Database.Database,
  schemaSql: string,
  budget: number = STATEMENT_BYTE_BUDGET,
): DumpResult {
  const parts: string[] = [
    '-- Generated by @pt-viewer/importer. Apply with e.g.',
    '--   wrangler d1 execute <db> --file <this file>',
    '',
    schemaSql.trimEnd(),
    '',
  ];
  let oversizedStatements = 0;

  for (const table of TABLES) {
    const rows = db
      .prepare(
        `SELECT ${table.columns.join(', ')} FROM ${table.name} ORDER BY ${table.orderBy}`,
      )
      .raw()
      .all() as unknown[][];
    for (const statement of buildInsertStatements(
      table.name,
      table.columns,
      rows,
      budget,
    )) {
      if (Buffer.byteLength(statement, 'utf8') > budget) oversizedStatements++;
      parts.push(statement);
    }
  }

  parts.push(
    "INSERT INTO stories_fts(stories_fts) VALUES('rebuild');",
    "INSERT INTO comments_fts(comments_fts) VALUES('rebuild');",
    '',
  );
  return { sql: parts.join('\n'), oversizedStatements };
}
