import type Database from 'better-sqlite3';

/** Rows per multi-row INSERT statement (keeps statement count and size sane). */
const BATCH_SIZE = 100;

/** Insert order respects foreign-key dependencies. */
const TABLES: { name: string; columns: string[]; orderBy: string }[] = [
  { name: 'projects', columns: ['id', 'slug', 'name'], orderBy: 'id' },
  { name: 'users', columns: ['id', 'name'], orderBy: 'id' },
  {
    name: 'stories',
    columns: [
      'id',
      'project_id',
      'title',
      'story_type',
      'current_state',
      'priority',
      'estimate',
      'requested_by_id',
      'created_at',
      'accepted_at',
      'deadline',
      'description',
      'url',
      'extra',
    ],
    orderBy: 'id',
  },
  {
    name: 'story_owners',
    columns: ['story_id', 'user_id', 'position'],
    orderBy: 'story_id, position',
  },
  {
    name: 'story_labels',
    columns: ['story_id', 'label'],
    orderBy: 'story_id, label',
  },
  {
    name: 'comments',
    columns: ['story_id', 'seq', 'author_id', 'commented_on', 'body'],
    orderBy: 'story_id, seq',
  },
  {
    name: 'tasks',
    columns: ['story_id', 'seq', 'description', 'status'],
    orderBy: 'story_id, seq',
  },
  {
    name: 'attachments',
    columns: ['story_id', 'filename', 'size', 'rel_path'],
    orderBy: 'story_id, filename',
  },
];

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'bigint') return value.toString();
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * Generate a single Cloudflare-D1-compatible SQL script that recreates the
 * whole dataset: schema DDL, batched multi-row INSERTs, then the two FTS
 * rebuild statements. No PRAGMA / BEGIN / COMMIT (wrangler handles batching).
 */
export function generateDump(db: Database.Database, schemaSql: string): string {
  const parts: string[] = [
    '-- Generated by @pt-viewer/importer. Apply with e.g.',
    '--   wrangler d1 execute <db> --file <this file>',
    '',
    schemaSql.trimEnd(),
    '',
  ];

  for (const table of TABLES) {
    const rows = db
      .prepare(
        `SELECT ${table.columns.join(', ')} FROM ${table.name} ORDER BY ${table.orderBy}`,
      )
      .raw()
      .all() as unknown[][];
    if (rows.length === 0) continue;
    for (let i = 0; i < rows.length; i += BATCH_SIZE) {
      const batch = rows.slice(i, i + BATCH_SIZE);
      const values = batch
        .map((row) => `(${row.map(sqlLiteral).join(',')})`)
        .join(',\n');
      parts.push(
        `INSERT INTO ${table.name} (${table.columns.join(', ')}) VALUES\n${values};`,
      );
    }
  }

  parts.push(
    "INSERT INTO stories_fts(stories_fts) VALUES('rebuild');",
    "INSERT INTO comments_fts(comments_fts) VALUES('rebuild');",
    '',
  );
  return parts.join('\n');
}
